# Generated by Django 2.2.3 on 2019-08-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(help_text='Unique ID for this particular area', primary_key=True, serialize=False)),
                ('name_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id_facility', models.AutoField(help_text='Unique ID for this facility', primary_key=True, serialize=False)),
                ('name_facility', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id_guide', models.AutoField(primary_key=True, serialize=False)),
                ('firstName_guide', models.CharField(max_length=100)),
                ('lastName_guide', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id_organizator', models.AutoField(primary_key=True, serialize=False)),
                ('firstName_organizator', models.CharField(max_length=100)),
                ('lastName_organizator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id_incharge', models.AutoField(primary_key=True, serialize=False)),
                ('firstName_incharge', models.CharField(max_length=100)),
                ('lastName_incharge', models.CharField(max_length=100)),
                ('id_facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id_excursion', models.AutoField(help_text='Unique ID for this particular excursion', primary_key=True, serialize=False)),
                ('occasion_excursion', models.CharField(help_text='Enter an excursion occasion (e.g. JEMS 12 etc.)', max_length=200)),
                ('date_excursion', models.DateField(help_text='Enter an excursion date')),
                ('time_excursion', models.CharField(help_text='Enter an excursion time period', max_length=200)),
                ('language_excursion', models.CharField(help_text='Enter an excursion language', max_length=200)),
                ('auditory_excursion', models.CharField(help_text='Enter an excursion auditory', max_length=200)),
                ('participants_excursion', models.IntegerField(help_text='Enter count of an excursion participants')),
                ('age_excursion', models.CharField(help_text='Enter an age of excursion participants', max_length=6)),
                ('id_area', models.ManyToManyField(help_text='Select a desired areas for this excursion', to='app.Area')),
                ('id_facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Facility')),
                ('id_guide', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Guide')),
                ('id_organizator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Organizator')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='id_facility',
            field=models.ManyToManyField(to='app.Facility'),
        ),
    ]
