# Generated by Django 2.2.4 on 2019-12-04 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(help_text='Unique ID for this particular area', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(help_text='Unique ID for this facility', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+71234567890'. Up to 17 digits allowed.", regex='^\\+?1?\\d{9,17}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Readed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Chat', verbose_name='Chat')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Facility')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ManyToManyField(to='app.Facility')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id_excursion')),
                ('occasion', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('stop_time', models.TimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(max_length=200)),
                ('auditory', models.CharField(max_length=200)),
                ('participants', models.IntegerField()),
                ('confirmed_guide', models.BooleanField(default=False)),
                ('confirmed_incharge', models.BooleanField(default=False)),
                ('areas', models.ManyToManyField(to='app.Area')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Facility')),
                ('guide', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_guide', to='app.Guide')),
                ('incharge', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_incharge', to='app.Incharge')),
                ('organizator', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_organizator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='excursion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Excursion'),
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='area',
            name='facility',
            field=models.ManyToManyField(to='app.Facility'),
        ),
    ]
