# Generated by Django 2.2.6 on 2019-11-27 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(help_text='Unique ID for this particular area', primary_key=True, serialize=False)),
                ('name_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id_facility', models.AutoField(help_text='Unique ID for this facility', primary_key=True, serialize=False)),
                ('name_facility', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Readed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Chat', verbose_name='Chat')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Facility')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id_excursion', models.AutoField(auto_created=True, help_text='Unique ID for this particular excursion', primary_key=True, serialize=False, verbose_name='id_excursion')),
                ('occasion_excursion', models.CharField(max_length=200)),
                ('date_excursion', models.DateField(help_text='Enter date of excursion')),
                ('time_period_excursion', models.CharField(max_length=200)),
                ('language_excursion', models.CharField(max_length=200)),
                ('auditory_excursion', models.CharField(max_length=200)),
                ('participants_excursion', models.IntegerField()),
                ('confirmed_guide', models.BooleanField(default=False)),
                ('confirmed_incharge', models.BooleanField(default=False)),
                ('areas', models.ManyToManyField(to='app.Area')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Facility')),
                ('guide', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_guide', to=settings.AUTH_USER_MODEL)),
                ('incharge', models.ForeignKey(default='', help_text='Responsible for the excursion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_incharge', to=settings.AUTH_USER_MODEL)),
                ('organizator', models.ForeignKey(default='', help_text='Organizator of this excursion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_organizator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='excursion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Excursion'),
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='area',
            name='id_facility',
            field=models.ManyToManyField(to='app.Facility'),
        ),
    ]
