# Generated by Django 2.2.4 on 2020-01-14 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_Excursion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 14, 13, 47, 47, 529792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='stop_time',
            field=models.TimeField(default=datetime.datetime(2020, 1, 14, 13, 47, 47, 547326, tzinfo=utc)),
        ),
    ]
