# Generated by Django 2.2.3 on 2019-08-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='time_excursion',
            new_name='time_period_excursion',
        ),
        migrations.RenameField(
            model_name='organizator',
            old_name='firstName_organizator',
            new_name='name_organizator',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='id_organizator',
        ),
        migrations.RemoveField(
            model_name='organizator',
            name='lastName_organizator',
        ),
        migrations.AddField(
            model_name='excursion',
            name='name_organizator',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
