# Generated by Django 2.2.3 on 2019-08-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190808_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='date_excursion',
            field=models.DateField(blank=True, default='', help_text='Enter an excursion date', null=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='id_excursion',
            field=models.AutoField(auto_created=True, help_text='Unique ID for this particular excursion', primary_key=True, serialize=False, verbose_name='id_excursion'),
        ),
    ]
