# Generated by Django 2.2.4 on 2020-01-14 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200114_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='stop_time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
