# Generated by Django 2.2.4 on 2020-01-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200114_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='confirmed_guide',
            new_name='confirmed_by_guide',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='confirmed_incharge',
            new_name='confirmed_by_incharge',
        ),
    ]
