# Generated by Django 2.2.3 on 2019-08-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190808_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='date_excursion',
            field=models.DateField(help_text='Enter an excursion date'),
        ),
    ]
