# Generated by Django 2.2.6 on 2019-11-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='guide',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_guide', to='app.Guide'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='incharge',
            field=models.ForeignKey(default='', help_text='Responsible for the excursion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_incharge', to='app.Incharge'),
        ),
    ]
