# Generated by Django 2.2.4 on 2020-01-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200120_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='auditory',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='occasion',
            new_name='target_audience',
        ),
    ]
