# Generated by Django 2.2.3 on 2019-08-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190808_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='age_excursion',
            field=models.CharField(help_text='Enter age of excursion participants', max_length=6),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='auditory_excursion',
            field=models.CharField(help_text='Enter auditory of excursion ', max_length=200),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='date_excursion',
            field=models.DateField(help_text='Enter date of excursion'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='id_facility',
            field=models.ForeignKey(help_text='Select desired facility', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Facility'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='id_guide',
            field=models.ForeignKey(help_text='Select desired guide for this excursion', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Guide'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='language_excursion',
            field=models.CharField(help_text='Enter language of excursion', max_length=200),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='name_organizator',
            field=models.CharField(help_text='Enter the name of the excursion organizator', max_length=200),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='occasion_excursion',
            field=models.CharField(help_text='Enter occasion of excursion  (e.g. JEMS 12 etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='participants_excursion',
            field=models.IntegerField(help_text='Enter count of excursion participants'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='time_period_excursion',
            field=models.CharField(help_text='Enter time period of excursion', max_length=200),
        ),
    ]
