# Generated by Django 2.2.4 on 2019-08-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190820_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='firstName_guide',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='lastName_guide',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='firstName_incharge',
        ),
        migrations.RemoveField(
            model_name='incharge',
            name='lastName_incharge',
        ),
    ]
