# Generated by Django 2.2.4 on 2019-08-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190820_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='id_area',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='excursion',
            old_name='id_facility',
            new_name='facility',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='guide',
            field=models.ForeignKey(default='', help_text='Select desired guide for this excursion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_guide', to='app.Guide'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='incharge',
            field=models.ForeignKey(default='', help_text='Responsible for the excursion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_incharge', to='app.Incharge'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='organizator',
            field=models.ForeignKey(default='', help_text='Enter the name of the excursion organizator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_organizator', to='app.Organizator'),
        ),
    ]
