# Generated by Django 2.2.4 on 2019-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190821_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
