# Generated by Django 2.2.4 on 2019-08-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_excursion_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='status',
            new_name='confirmed',
        ),
    ]
